### ISSUE TITLE
Now OSS plan limits docker image size to 100 MiB

### ISSUE THREAD

**Issue by ameistad** [develomark/prisma-now#2]
When i try to deploy the image on Now i get an error saying that the built image exceeds the 100MiB limit. Do I need to upgrade my plan to premium to deploy the prisma image?

**Comment by develomark** [comment]
I'd say so. I've not tested with non-premium. I didn't actually know you could do docker deploys with OSS plan.

**Comment by develomark** [comment]
Closing.

**Comment by rjsandman** [comment]
According to Now this has nothing to do with the plan type.  They are limiting the build image size to 100mb on all plans.  Their recommendation is to do a multi-stage build.  @develomark Do you know how to do this with your example?
