### ISSUE TITLE
More explanation of Dockerfile

### ISSUE THREAD

**Issue by jhalborg** [develomark/prisma-now#4]
Hey, 

Thanks again for a great example and guide! It's very helpful. 

I wonder if you could add some comments, explaining what happens in the Dockerfile for Docker-n00bs like myself? :-D It's great that it works, but it'd be nice to know what each line does and why it's necessary.

**Comment by develomark** [comment]
Done @jhalborg as requested.

All the best.

**Comment by develomark** [comment]
Closed
